### ISSUE TITLE
Chat filter not working again.

### ISSUE THREAD

**Issue by ProjectRevoTPP** [jpgohlke/twitch-chat-filter#170] opened 2015-05-25 19:35 UTC
Self explanatory.

**Comment by hugomg** [comment] 2015-05-25 19:38
No such thing as a "self explanatory bug" :)

What browser are you using? How are you running TPP (greasemonkey, bookmarklet, etc)? Do any error messages appear in the Javascript console? (you can open the console with F12 on most browsers)

**Comment by ProjectRevoTPP** [comment] 2015-05-25 19:56
Firefox, Greasemonkey. Havent tried total reset of firefox, will try soon.

**Comment by aaaaaa123456789** [comment] 2015-05-30 03:42
The chat filter works when enabled (i.e., by entering the command via console and/or using the bookmark), but only for messages already in the chat; it doesn't filter new ones. Adding a new instance of the filter repeats the process, but new, incoming messages never get filtered.
(I'm on the latest version of Chrome, if that matters.)

**Comment by iriomote14** [comment] 2015-05-30 04:34
So I think I found a fix for the chat filter thing ... I tested it out locally, and it seems to be working correctly. Basically, I replaced:

add_initializer(function(){
    var View_proto = require("web-client/views/line")["default"].prototype;

    // New lines
    var original_didInsertElement = View_proto.didInsertElement;
    View_proto.didInsertElement = function() {
        original_didInsertElement.apply(this, arguments);

        var view = this.$();
        var matches = matches_filters(this.get("context.model.message"), this.get("context.model.from"));
        for (var filter in matches) {
            view.toggleClass(filter, matches[filter]);
        }
    };

with the following:

add_initializer(function(){
    var View_proto = require("web-client/components/chat-line")["default"].prototype;

    // New lines
    var original_didInsertElement = View_proto.didInsertElement;
    View_proto.didInsertElement = function() {
        original_didInsertElement.apply(this, arguments);
        var view = this.$();
        var matches = matches_filters(this.get("msgObject.message"), this.get("msgObject.from"));
        for (var filter in matches) {
            view.toggleClass(filter, matches[filter]);
        }
    };

I'm not too confident in my Javascript abilities, so I'll leave it to you to determine if this should go in as such. But you can at least see where the problem is based on what I've written here - hopefully it's enough to go on.

Thanks so much for this filter - it's always great to use it! :)

**Comment by MattiasBuelens** [comment] 2015-05-30 21:39
@iriomote14 You're absolutely correct. Twitch has changed some of the names in their JavaScript code, so our monkey patch were broken.

Version 3.2 is now up with a fix for this. :)

**Closed by MattiasBuelens** 2015-05-30 21:39 UTC
